site_name: "Una página de amor"
nav:
  - Principal: index.md
  - Peliculas y series: peliculas.md
  - Canciones: canciones.md
  - Poemas: poemas.md
  - Juegos: juegos.md
  - Recuerdos: recuerdos.md
  - Secreto: secreto.md
theme:
  name: 'material'
  palette:
    primary: 'pink'
    accent: 'red'

