site_name: "Para Laura"
nav:
  - Home: index.md
  - Poemas: poemas.md
  - Canciones: canciones.md
  - Peliculas: peliculas.md
theme:
  name: 'material'
  palette:
    primary: 'pink'
    accent: 'red'

