site_name: "Prueba a navegar por estos sitios :3"
nav:
  - Principal: index.md
  - Poemas: poemas.md
  - Canciones: canciones.md
  - Peliculas: peliculas.md
  - Secreto: secreto.md
theme:
  name: 'material'
  palette:
    primary: 'pink'
    accent: 'red'

